#+title: Change log of xkb-mode
#+author: James Dyer
#+email: captainflasmr@gmail.com
#+language: en
#+options: ':t toc:nil author:nil email:nil num:nil title:nil
#+startup: showall

This document contains the release notes for each tagged commit on the
project's main git repository: [[https://github.com/captainflasmr/xkb-mode]].

With a roadmap and issues also supplied.

* Whats New

Version 0.2.0

- Correct version from 0.6.0 to 0.2.0 to reflect the actual stage of development.
- Remove the 'Alternatives' section, streamlining the introduction.
- Improve code formatting for better readability and maintenance. This includes more consistent use of newlines and arrangement of font lock faces.
- Use `#'` prefix for function symbols as a best practice, explicitly marking `xkb-indent-line` as a function, enhancing code clarity.

* ISSUES

NONE

* ROADMAP

** TODO function to set xkb file to latched sticky keys
** TODO function to set xkb file locked sticky keys
** TODO function to map RAlt to Ctrl

* Versions

** 0.1.0 on <2024-05-05 Sun>

Inception

* Testing

developing locally using:
#+begin_src elisp
(use-package xkb-mode
   :load-path "~/repos/xkb-mode"
#+end_src

commiting to github then removing ~/.config/emacs/elpa/xkb-mode, changing emacs init to:

#+begin_src elisp
(use-package xkb-mode
  :vc (:fetcher github :repo "captainflasmr/xkb-mode")
#+end_src

restart emacs and test
